name = "TensorDecompSTFT"
uuid = "7cc29fb0-3c2d-4675-a505-a9bcd44018e8"
authors = ["Nicholas Richardson <njericha@math.ubc.ca>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
